In [15]:
import numpy as np

dummy = np.array([[1, 2, 3, 4, 5, 6],
         [7, 8, 9, 10, 11, 12]])

dummy = dummy.transpose()
print(np.shape(dummy))
print(dummy[:, 0])

(6, 2)
[1 2 3 4 5 6]


In [2]:
scaled_dummy = np.array(dummy)

scaled_dummy[:, 0] = (scaled_dummy[:, 0] - 12)

In [26]:
13 % 5

3

In [31]:
length = 11
pad_len = int(abs(len(dummy) - length) / 2)

pad_dummy = []
for i in range(2):
    pad = dummy[:, i]
    pad = np.pad(pad, (pad_len,))

    if len(pad) < length:
        pad = np.append(pad, [0])
    pad_dummy.append(pad)

pad_dummy = np.transpose(pad_dummy)

print(np.shape(pad_dummy))

(11, 2)


In [4]:
length = 4
shrink_dummy = []

for i in range(2):
    shrk = dummy[:length, i]
    shrink_dummy.append(shrk)

shrink_dummy = np.transpose(shrink_dummy)
print(shrink_dummy)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]]


In [14]:
dummy = np.array(dummy)

for idx in range(np.shape(dummy)[1]):

    print(idx)

dummy.transpose()

0
1


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
dummy.transpose()

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
print(len(dummy[:, 1]))

6
